server/src/api/v1/upload_path.rs

Fixes an issue which occurs when uploading NAR files that aren’t chunked

fix null insertion in chunkref table

---

Cargo.lock
client/Cargo.toml

I just ran into an issue using attic with a self hosted CA: the attic client does not use the certificate store of the system. I don't know if this is an intentional design decision. If it isn't this PR should fix the issue.

use system certificate store for attic client

---

nixos/atticd.nix

Currently, the output of the atticadm wrapper is cluttered by the output of systemd-run. This pull request adds a `--quiet` flag to suppress them.

nixos: Suppress systemd-run's output in atticadm wrapper

---

nixos/atticd.nix

This is useful for postgreSQL's peer authentication method (which checks if the authenticating user's name agrees with the role name).
This change should be backward compatible.

nixos: Make the group and user name under which attic runs configurable

---

server/src/api/v1/upload_path.rs

I was still encountering failures due to narinfo files being too large,
even with the increased 64kiB limit. This commit increases it to 1MiB
which is hopefully larger than any “reasonable” derivation, while also
not being too large for the server to keep in memory at once.

Increase narinfo size limit to 1MiB

---

.github/workflows/build.yml

Add steps to build & push image to GitHub's container registry.
Steps setup to:
- tag image with git commit SHA if it's a regular push event
- tag image with git's tag minus `v` prefix if it's a tag build (I didn't update the job to run on tag events, though) 
- tag image as `latest` if it's a build on `main` branch.
Validated on my fork.
Closes #16

feat: Build & Push images as part of CI

---

crane.nix

Suppress this annoying warning (https://github.com/ipetkov/crane/issues/281):
```console
$ nix build github:zhaofengli/attic
trace: warning: crane cannot find version attribute in /nix/store/qdggd1m9zk6kq29fc3kvf6prb8xabdfr-source/Cargo.toml, consider setting `version = "...";` explicitly
```

crane.nix: Suppress warning of missing version attribute in Cargo.toml

---

client/src/config.rs

I encountered this during trying the demo, when I changed my url to something shorter:
```
❯ attic login local http://localhost:8080 ey..ok
✍ Configuring server "local"
❯ attic login local http://khonsu:8080 ey..ok
✍ Overwriting server "local"
❯ bat ~/.config/attic/config.toml
1   │ default-server = "local"
2   │
3   │ [servers.local]
4   │ endpoint = "http://khonsu:8080"
5   │ token = "ey..ok"
6   │ k
```
and attic failed trying to parse the toml :yum:

fix: writing config does not truncate

---

attic/src/nix_store/bindings/nix.cpp

This allows connecting to other stores by setting `NIX_REMOTE`, or the `store` setting in `nix.conf`. This can be helpful for migrating from a flat-file binary cache, using chroot stores, or otherwise pushing from more varied stores:
NIX_REMOTE=file:///var/lib/nix-binary-cache attic push magic $paths

Open the default store, not `auto`

---

nixos/atticd.nix

follow-up to 1a3b6513b02202198bb497608d0cedc45119799b

nixos: use configured user in admin wrapper

---

flake.nix

Before this patch we get:
error: don't yet have a `targetPackages.darwin.LibsystemCross for x86_64-apple-darwin`

Make nix flake show --all-systems work

---

integration-tests/basic/default.nix
server/src/storage/local.rs

Didn't actually tested the code. Maybe someone else can :)

implement sharding

---

client/src/api/mod.rs
client/src/command/login.rs
client/src/command/use.rs
client/src/config.rs

This allows to configure the client through nixos/home-manager while keeping the secrets separate.

client: allow storing the client token in a separate file

---

nixos/atticd.nix

Prevents "read only storage" errors when setting a non-default storage path.

nixos: add storage path to ReadWritePaths

---

client/src/cache.rs

When using attic from the overlay it seems to be using rust 1.75 (im on nixos-unstable) which errors the build because of this un-used import. 
Might be worth to pin the rust version in the nix build instead of using whats in nix pkgs for the overlay at least.
Verified the fix by updating my flake input to this branch and it built without issue

Remove un-used import

---

nixos/atticd.nix

Which we discovered did not happen automatically during a database switch.

nixos: restart atticd on failure

---

attic/build.rs
crane.nix
flake.lock
flake.nix
package.nix

Nix 2.19 introduced a change [0] that broke how we compile our libnixstore bindings, which requires adding an additional include directory when we compile them.
I also included a semi-related maintenance change that I had to apply when fixing this, let me know if you'd rather pull those in from a separate PR.
[0]: https://github.com/NixOS/nix/commit/b461cac21aa5b9127d230ed3f1a1ca8e8266fb60

Fix build on Nix 2.19+

---

server/src/gc.rs

This change fixes the immediate issue documented by #115.
There are some notable caveats though: for both mysql and sqlite, the parameter limits are configurable in the database, so my choice to use the defaults isn't adequate (but it is at least better than having no limit at all).
I think the more sensible and general approach that would solve both of these problems would be to:
- Limit `orphan_chunks` to something static and small, e.g 300 results.
- Use chained `OR`s instead of `IN` to get the most performant query possible.
... I didn't implement that though because we need something that brings attic back into service ASAP and I think that change is much more invasive than the one I'm proposing here and wanted to feel out @zhaofengli's receptiveness to that kind of change.
[EDIT] …

gc.rs: `LIMIT` number of `orphan_chunks`, fixes #115

---

server/src/api/binary_cache.rs

Closes https://github.com/zhaofengli/attic/issues/124.
Unless other knowledge comes to light, it appears that that was actually caused by an error in the actual stream of data itself -- I tested this by uploading something (with the storage backend as local), then manually messing with the database to change the `remote_file` and `remote_file_id` columns on the `chunk` table to point to some bogus (but valid-syntax) location in an S3 bucket. When trying to download, I would see errors from Nix but nothing from attic. Adding this print rectifies that.

Log stream errors

---

Cargo.lock
token/Cargo.toml
token/src/lib.rs
token/src/tests.rs

I added a test first, so that this kind of issue cannot happen again. If you check out this PR and run the tests before and after the switch to `IndexMap`, you should get a test failure before and a test success after.
See also https://github.com/zhaofengli/attic/issues/133 for an issue that was caused by the random ordering from a HashMap.
Closes #133.

token: switch to using IndexMap for consistent ordering of entries

---

client/src/config.rs

Any ordinary file will contain at least a trailing newline which cannot be included in the bearer header. Trim all leading/trailing whitespace.

trim token-file contents

---

server/src/lib.rs

I use attic on a "homelab" (really an old tower in my office), and I noticed that pushing to attic-server was almost unbearably slow for large files. 
I noticed some strange behavior: the upload would race to 100%, but then hang there for awhile, thus reducing throughput.
To investigate, I added some opentelemetry instrumentation, and then sent that to a free honeycomb account. Disclosure: honeycomb is my employer. That code is not in this PR, but I can PR that code upon request - it's just standard tracing-opentelemetry code, and isn't vendor-specific :)
Anyways, the initial investigation proved fruitful:
In the above, I'm tracing the [upload_chunk function](https://github.com/zhaofengli/attic/blob/717cc95983cdc357bc347d70be20ced21f935843/server/src/api/v1/upload_path.rs#L627). Notably, …

sqlite-specific performance tuning

---

.github/install-attic-ci.sh
.github/workflows/build.yml
ci-installer.nix

Also hotfixes the current install-attic-ci.sh.
Fixes #145.

ci-installer: Remove drvPath from fake derivation

---

server/src/api/binary_cache.rs

The call to `into_inner()` discards the wrapper type constructed by `map_err()`. So instead, `map_err()` the actual stream, and call `Body::from_stream` on the wrapped stream.
---
This was originally fixed in https://github.com/zhaofengli/attic/pull/137, but the update to axum 0.7 in https://github.com/zhaofengli/attic/pull/138 migrated that functionality slightly incorrectly.

fixup: stream error logging

---

.github/workflows/build.yml
Cargo.lock
attic/Cargo.toml
attic/build.rs
attic/src/nix_store/bindings/nix.cpp
flake.lock
flake.nix

The way I had to upgrade nix 2.24 is a bit hacky especially since it's not in nixos 24.05.

attic-client: fix build against Nix 2.24

---

Cargo.lock
attic/Cargo.toml

Remove the git dependency now that upstream has release 0.2.0.

Update nix-base32 crate

---

flake.nix

Missed this when modifying #159. Fixes mixing different versions of headers and libraries.
There will be a convenient way to test different Nix versions in the devShell soon.

flake.nix: Use default Nix headers in devShell

---

flake.lock
flake.nix
flake/devshells.nix
flake/packages.nix

Another small batch of miscellaneous trivial cleanups.

flake: Remove flake-utils, misc cleanup

---

attic/build.rs
crane.nix
flake.lock
flake/devshells.nix

flake: Follow package Nix version in dev shell

---

integration-tests/basic/default.nix
nixos/atticd.nix

Without --pipe stderr and stdout are combined, breaking scripts that use atticd-atticadm when it generates warnings.
Before:
~~~console
/nix/store/rnvn0g8qfnwspgy5fl14f5r438labrh8-atticadm: line 3: cd: /root: Permission denied
Warning: Failed to change directory to /root
HolTYkSVSqLp+7SMzwfkOoj6X5Baa5oVKsrSUSv04wGMcSM1f2hFnLP6mPYguZwYWDaRCCZ0Sl/7X/iO9wvNVuKCgi37ib2z06Jbj59j1MeKQ2CUFWpYjGzXQMq96Qh84W8JTg==
~~~
After:
~~~console
HolTYkSVSqLp+7SMzwfkOoj6X5Baa5oVKsrSUSv04wGMcSM1f2hFnLP6mPYguZwYWDaRCCZ0Sl/7X/iO9wvNVuKCgi37ib2z06Jbj59j1MeKQ2CUFWpYjGzXQMq96Qh84W8JTg==
~~~

Use --pipe for systemd-run

---

client/src/command/push.rs
client/src/push.rs

This adds a new flag (`-i`/`--stdin`) to the `push` subcommand of the attic client. This would  resolve #175 .
Note that there is also #118 , which implements a similar behavior as a fallback for the `push` command.

attic-client/push: Add flag to read paths from stdin

---

server/src/config.rs

After #177, having an empty `[jwt]` works but omitting it entirely results in an error. We should support this.
Fixes #178.

server/config: Allow omitting jwt section entirely

---

server/src/config.rs
token/src/lib.rs
token/src/tests.rs

Regression from #177 that erroneously required HS256 secrets to be valid UTF-8. Also fail fast on token decoding errors instead of silently ignoring them.
Fixes #180.

token: Don't require valid UTF-8 for HS256 secrets

---

client/src/command/push.rs
integration-tests/basic/default.nix

Some miscellaneous fixes to `attic push --stdin`.
Now it suggests `--stdin` if stdin isn't interactive (e.g., when you are trying to pipe to it).

client/push: Misc fixes

---

nixos/atticd.nix

Some people are using the NixOS module in this repo with an older atticd from nixpkgs (#184). Since the NixOS module sets a placeholder RS256 secret which the nixpkgs version doesn't support, config checking breaks.
We don't want to support such use case in general, but in this specific case I think setting a hardcoded HS256 secret is nicer than generating an RS256 keypair every time.
---
To reiterate, the NixOS module in this repo is coupled to the atticd version here and mixing the versions is unsupported. This PR happens to make it work for the moment, but it may very well break in the future.

nixos: Switch back to setting a placeholder HS256 secret

---

server/src/api/binary_cache.rs
server/src/error.rs

The default Display / `{}` formatter only shows the outermost error. We have to use `{:#}` to show all the errors in the chain. This will make stream errors somewhat more informational.
Before:
Stream error: Storage error: service error
After:
Stream error e=Storage error: service error: NoSuchKey: The specified key does not exist.: NoSuchKey: The specified key does not exist.
(after I manually mucked with the DB to change the S3 url for an item to a non-existent name)

Display anyhow error chains better

---

flake/packages.nix

For static builds let's link against Nix 2.18 for now for compatibility. Fixes #189.
Undraft after #190.
Will tweak the CI pipeline to add static builds in a separate PR (build test, integration test, attic-ci-installer).

flake/packages: Update patch for static builds

---

.github/workflows/build.yml
server/src/api/binary_cache.rs

Probably not the cleanest way to do it, but it worked based on my testing and I was trying to figure out an (unrelated) issue that could have had something to do with the Content-Type always being `application/octet-stream` from Attic. Just sending this anyways because it seems unintended for this to always be `application/octet-stream` compared to other Nix binary caches out there that do send `application/x-nix-nar`.

fix application/x-nix-nar Content-Type not being applied

---

nixos/atticd.nix

This reverts commit 94fa54632d460d7ac68c635260cbd79c8ed082f1.
Breaks usage of the attic package, to avoid having to build attic twice for server and client.
See also https://github.com/zhaofengli/attic/pull/186#discussion_r1827083331

Revert "nixos: Use lib.getExe"

---

book/src/tutorial.md

`nix-shell https://github.com/zhaofengli/attic/tarball/main -A demo` is outdated and fails with:
```
error: attribute 'demo' in selection path 'demo' not found
```
This PR updates the tutorial instructions to instead use `nix shell github:zhaofengli/attic` which helps locate `attic` and `atticd`:
```
$ nix shell github:zhaofengli/attic
$ which attic   
/nix/store/34hyvbzg5gv0jwl8vajsr16m4f3dy6l4-attic-0.1.0/bin/attic
which atticd
/nix/store/34hyvbzg5gv0jwl8vajsr16m4f3dy6l4-attic-0.1.0/bin/atticd
```

Updating tutorial instructions for running demo

---

flake/packages.nix

This PR fixes #272 . Since we have already copied binaries to the root in:
https://github.com/zhaofengli/attic/blob/687dd7d607824edf11bf33e3d91038467e7fad43/flake/packages.nix#L104-L112
using `${self'.packages.attic-server}/bin/atticd` in the entrypoint will trigger another unnecessary copy.

fix(docker): retain only one binary in the docker image

---

book/src/user-guide/README.md

This PR adds a small section that explains how to enable a cache declaratively with NixOS inside the `configuration.nix` which will help NixOS users setting up their first binary cache more easily.
> I've myself spend some time researching how this is possible with attic so I tried to save other people that time.

docs: usage instructions for binary cache with NixOS (declaratively)
